"""Generate `src/scanner/unicode.rs`: the character classes the native source scanner needs, as
CPython computes them, for every Unicode version a supported CPython ships.

The Python scanner (`pydeno._preflight_reference`) decides word boundaries with `re`'s ``\\w`` and
``\\s`` and with ``str.isalnum`` / ``isspace`` / ``isdigit`` / ``isidentifier``. Those follow the
Unicode database built into the running CPython, which differs between minor versions (3.10 ships
Unicode 13.0, 3.14 ships 16.0). The native scanner must give identical findings, so it carries one
column of flags per Unicode version and is told which one the running interpreter uses.

Usage (one interpreter per Unicode version; each is run as a child process)::

    python scripts/gen_scanner_unicode.py python3.10 python3.11 python3.12 python3.13 \\
        python3.14 python3.15

Re-run it when a new CPython (and so a new Unicode version) is supported, then rebuild.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "scanner" / "unicode.rs"

#: Run in each interpreter: its Unicode version and the flag runs over every code point.
#: Bits: 1 isalnum (so ``\w`` is isalnum or ``_``), 2 isspace (== ``\s``), 4 isdigit,
#: 8 isidentifier (a one-character identifier: XID_Start or ``_``).
_CHILD = r"""
import json, re, sys, unicodedata
word, space = re.compile(r"\w"), re.compile(r"\s")
runs, prev = [], None
for cp in range(0x110000):
    ch = chr(cp)
    alnum = ch.isalnum()
    assert alnum == bool(word.match(ch)) or ch == "_", cp
    assert ch.isspace() == bool(space.match(ch)), cp
    flags = alnum | ch.isspace() << 1 | ch.isdigit() << 2 | ch.isidentifier() << 3
    if flags != prev:
        runs.append((cp, flags))
        prev = flags
json.dump({"version": unicodedata.unidata_version, "runs": runs}, sys.stdout)
"""


def _flags_at(runs: list[tuple[int, int]], starts: list[int]) -> list[int]:
    """Each merged start's flags in one version's runs."""
    out, k = [], 0
    for start in starts:
        while k + 1 < len(runs) and runs[k + 1][0] <= start:
            k += 1
        out.append(runs[k][1])
    return out


def main(interpreters: list[str]) -> None:
    tables: dict[str, list[tuple[int, int]]] = {}
    for exe in interpreters:
        data = json.loads(
            subprocess.run(
                [exe, "-c", _CHILD], check=True, capture_output=True, text=True
            ).stdout
        )
        tables[data["version"]] = [tuple(r) for r in data["runs"]]
    versions = sorted(tables, key=lambda v: tuple(int(p) for p in v.split(".")))
    if len(versions) > 8:
        raise SystemExit("at most 8 Unicode versions fit the packed flags")
    starts = sorted({s for runs in tables.values() for s, _ in runs if s >= 0x80})
    starts = [0x80] + [s for s in starts if s != 0x80]
    columns = [_flags_at(tables[v], starts) for v in versions]
    packed = [
        sum(col[i] << (4 * c) for c, col in enumerate(columns))
        for i in range(len(starts))
    ]
    ascii_runs = [_flags_at(tables[v], list(range(0x80))) for v in versions]
    if any(r != ascii_runs[0] for r in ascii_runs):
        raise SystemExit("ASCII classes differ between Unicode versions")

    def rows(values: list[int], fmt: str) -> str:
        items = [fmt.format(v) for v in values]
        return "\n".join(
            "    " + ", ".join(items[i : i + 10]) + ","
            for i in range(0, len(items), 10)
        )

    OUT.write_text(
        "// @generated by scripts/gen_scanner_unicode.py: do not edit by hand.\n"
        "//\n"
        "// Character classes as CPython computes them, one 4-bit column per Unicode version:\n"
        "// 1 isalnum, 2 isspace, 4 isdigit, 8 isidentifier.\n\n"
        f"pub(super) const VERSIONS: [&str; {len(versions)}] = {json.dumps(versions)};\n\n"
        "/// Flags of the ASCII range (identical in every version).\n"
        f"pub(super) const ASCII: [u8; 128] = [\n{rows(ascii_runs[0], '{}')}\n];\n\n"
        "/// Start of each run of equal flags above ASCII, ascending; the run ends at the next start.\n"
        f"pub(super) const STARTS: [u32; {len(starts)}] = [\n{rows(starts, '0x{:X}')}\n];\n\n"
        "/// The flags of each run, version `v` in bits `4 * v .. 4 * v + 4`.\n"
        f"pub(super) const FLAGS: [u32; {len(packed)}] = [\n{rows(packed, '0x{:X}')}\n];\n",
        encoding="utf-8",
    )
    print(
        f"{OUT}: {len(versions)} versions ({', '.join(versions)}), {len(starts)} runs"
    )


if __name__ == "__main__":
    main(sys.argv[1:] or [sys.executable])
